FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/Internal/Internal.csproj", "Internal/"]
RUN dotnet restore "Internal/Internal.csproj"
COPY . .
WORKDIR "/src/Internal"
RUN dotnet build "Internal.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Internal.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Internal.dll"]
